window.MESA42_OBRAS = [
  {
    titulo: 'O Surgimento de uma Lenda',
    autor: 'Neto',
    data: '2026-09-22',
    dataLabel: '22 de setembro de 2026',
    categoria: 'Conto',
    tipos: ['textos'],
    resumo: 'Guilherme só queria terminar mais um dia, assistir a um torneio de Flesh and Blood e evitar qualquer contato desnecessário com o trabalho, com a ex e, se possível, com a vida adulta. Mas um iogurte esquecido na geladeira muda seus planos de forma bastante inconveniente. Entre decisões ruins, ciência duvidosa, partidas de card game e consequências cada vez mais estranhas, começa a história improvável de uma lenda.',
    url: 'obras/o-surgimento-de-uma-lenda/',
    imagem: 'obras/o-surgimento-de-uma-lenda/assets/lactococos.webp',
    imagemAlt: 'LactoCocos de terno diante de uma janela lunar com a Terra ao fundo, em ilustração retrô de ficção científica',
    cta: 'Ler conto',
    palavras: 2056,
    tempoLeitura: 11,
    leituraAdultos: true,
    avisoLeitura: 'Linguagem imprópria, drogas, escatologia, violência e morte.',
    anuncio: 'O Surgimento de uma Lenda já está no ar. Um iogurte esquecido, ciência duvidosa e o nascimento improvável de LactoCocos.',
    tags: ['ficção científica', 'humor absurdo', 'Flesh and Blood', 'LactoCocos']
  },
  {
    titulo: 'Interface gosmenta',
    autor: 'Neto',
    data: '2026-09-19',
    dataLabel: '19 de setembro de 2026',
    categoria: 'Transmissão fictícia',
    tipos: ['textos'],
    resumo: 'Uma live sobre Flesh and Blood sai do controle quando espectadores de outras galáxias começam a discutir a estranha anatomia do apresentador.',
    url: 'obras/interface-gosmenta/',
    imagem: 'obras/interface-gosmenta/assets/interface-gosmenta.webp',
    imagemAlt: 'Apresentador terrestre em uma live cercado por alienígenas e códigos do tradutor visual',
    cta: 'Assistir à transmissão',
    palavras: 1150,
    tempoLeitura: 6,
    leituraAdultos: true,
    avisoLeitura: 'Linguagem imprópria, anatomia alienígena, flerte interestelar e decisões questionáveis.',
    anuncio: 'Interface gosmenta já está no ar. Uma live terrestre, dois mil alienígenas e absolutamente nenhum controle do chat.',
    tags: ['ficção científica', 'humor absurdo', 'card game']
  },
  {
    titulo: 'Descoberta absurda no Reddit',
    autor: 'Neto',
    data: '2026-07-27',
    dataLabel: '27 de julho de 2026',
    categoria: 'Ficção documental',
    tipos: ['textos'],
    resumo: 'Um vídeo apagado, centenas de Túnicas destruídas e uma discussão arquivada revelam um comércio que talvez devesse ter permanecido escondido.',
    url: 'obras/descoberta-absurda-no-reddit/',
    imagem: 'obras/descoberta-absurda-no-reddit/assets/banner-descoberta-reddit.webp',
    imagemAlt: 'Notebook exibindo uma discussão online com conteúdo removido',
    cta: 'Ler arquivo',
    palavras: 1319,
    tempoLeitura: 7,
    leituraAdultos: true,
    avisoLeitura: 'Descrições de mutilação, linguagem explícita, violência e humor macabro.',
    anuncio: 'Descoberta absurda no Reddit já está no ar. Um vídeo apagado e centenas de Túnicas destruídas.',
    tags: ['ficção documental', 'humor macabro', 'Flesh and Blood', 'fórum arquivado']
  },
  {
    titulo: 'Paga meu TIX',
    autor: 'Neto',
    data: '2026-07-14',
    dataLabel: '14 de julho de 2026',
    categoria: 'Conto',
    tipos: ['textos'],
    resumo: 'Um acidente de trânsito, uma nave bethaniana e cinco mil TIX colocam Deva e Blorf no meio de uma negociação completamente razoável.',
    url: 'obras/paga-meu-tix/',
    imagem: 'obras/paga-meu-tix/assets/nave-avenida-america.webp',
    imagemAlt: 'Nave bethaniana sobre a Avenida América em meio ao trânsito de Cianorte',
    cta: 'Ler conto',
    palavras: 1983,
    tempoLeitura: 10,
    leituraAdultos: true,
    avisoLeitura: 'Palavrões, sexo, drogas digitais e decisões financeiras questionáveis.',
    anuncio: 'Paga meu TIX já está no ar. Deva e Blorf só queriam resolver um pequeno problema de trânsito.',
    tags: ['ficção científica', 'humor absurdo', 'card game']
  },
  {
    titulo: 'O anúncio do Grande Torneio Galáctico de Card Game',
    autor: 'Neto',
    data: '2026-07-10',
    dataLabel: '10 de julho de 2026',
    categoria: 'Reportagem fictícia',
    tipos: ['textos', 'series'],
    resumo: 'Milhares de naves retornam à Terra, a Lua entra em disputa e uma possível invasão se transforma no anúncio do maior torneio de card game do universo conhecido.',
    url: 'obras/anuncio-grande-torneio-galactico-card-game/',
    imagem: 'obras/anuncio-grande-torneio-galactico-card-game/assets/thumb-grande-torneio-galactico.png',
    imagemAlt: 'Plantão do Canal 5 sobre a chegada dos Galurianos e o anúncio do torneio galáctico',
    cta: 'Ler transmissão',
    palavras: 4597,
    tempoLeitura: 23,
    leituraAdultos: true,
    avisoLeitura: 'Palavrões, mutilações, pânico global e decisões diplomáticas questionáveis.',
    tags: ['reportagem fictícia', 'série', 'grande torneio galáctico', 'telejornal']
  },
  {
    titulo: 'O caso H4r78lump3r7 Fl0657r0p3d',
    autor: 'Neto',
    data: '2026-07-09',
    dataLabel: '9 de julho de 2026',
    categoria: 'Reportagem fictícia',
    tipos: ['textos', 'series'],
    resumo: 'Um relatório jornalístico sobre a carta Desmembramento Permanente, uma anomalia neuropsicogravitacional e o projeto artístico bilíngue recuperado de um designer sintético.',
    url: 'obras/caso-h4r78lump3r7-desmembramento-permanente/',
    imagem: 'obras/caso-h4r78lump3r7-desmembramento-permanente/assets/thumb-desmembramento-permanente.webp',
    imagemAlt: 'Arte da carta Desmembramento Permanente com Bethaniano e Alpha TRAPPIST',
    cta: 'Ler relatório',
    palavras: 3943,
    tempoLeitura: 20,
    leituraAdultos: true,
    avisoLeitura: 'Desmembramento, violência gráfica, mutilações e decisões artísticas questionáveis.',
    tags: ['ficção documental', 'projeto artístico', 'card game', 'série']
  },
  {
    titulo: 'Vença o campeão nacional',
    autor: 'Neto',
    data: '2026-07-03',
    dataLabel: '3 de julho de 2026',
    categoria: 'Jogo narrativo',
    tipos: ['interativos'],
    resumo: 'Um mini game de Flesh and Blood em que a leitura correta da mesa decide a final contra o campeão nacional.',
    resumoHome: 'Este minigame simula uma jogada de Flesh and Blood inspirada em um momento real e emocionante de partida. A proposta é estudar, na prática, janelas de prioridade, ações e reações dentro de um único turno. Em uma partida real, ainda seria preciso acompanhar o cemitério do oponente e lembrar as cartas usadas para pitch. Aqui, o cenário foi simplificado para focar nas decisões: temos instants defensivos na mão, ataques de alto custo, possibilidade de compra de cartas e um oponente capaz de atacar durante o nosso próprio turno.',
    url: 'obras/venca-o-campeao-nacional/',
    imagem: 'obras/venca-o-campeao-nacional/assets/arena-de-batalha.png',
    imagemAlt: 'Arena de batalha do mini game Vença o campeão nacional',
    cta: 'Jogar',
    tags: ['mini game', 'Flesh and Blood', 'final de partida']
  },
  {
    titulo: 'Command and Conquer',
    autor: 'Neto',
    data: '2026-07-02',
    dataLabel: '2 de julho de 2026',
    categoria: 'Visual novel seriada',
    tipos: ['series', 'interativos'],
    resumo: 'JP compra uma carta especial por um preço muito abaixo do mercado. Quando ela entra no deck, sua sorte muda — e a carta começa a parecer mais importante do que deveria.',
    url: 'obras/command-and-conquer/',
    imagem: 'assets/command-and-conquer-card-art.png',
    imagemAlt: 'Arte da obra Command and Conquer',
    cta: 'Ver capítulos',
    tags: ['série', 'visual novel', 'card game']
  },
  {
    titulo: 'Financiamento coletivo para salvar todas as cartas colecionáveis existentes',
    autor: 'Neto',
    data: '2026-05-12',
    dataLabel: '12 de maio de 2026',
    categoria: 'Site fictício interativo',
    tipos: ['interativos'],
    resumo: 'Uma campanha fictícia do NossoDinheiro para preservar, catalogar e proteger todas as cartas colecionáveis já impressas. Um projeto que começa como piada de colecionador e termina com cara de documento público impossível.',
    url: 'obras/financiamento-coletivo-cartas-nosso-dinheiro/',
    imagem: 'assets/nosso-dinheiro-logo.svg',
    imagemAlt: 'Logo fictício NossoDinheiro',
    imagemModo: 'contain',
    cta: 'Abrir experiência',
    tags: ['destaque', 'ficção documental', 'campanha falsa']
  }
];
